In [4]:
import pandas as pd
import numpy as np
import random
import os

random.seed(42)
np.random.seed(42)

print("Libraries loaded successfully")

Libraries loaded successfully

In [7]:
DATA_PATH = "../data/raw/Task_Categories.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)

df.head(10)

Dataset shape: (20122, 3)

                Task Description Category        Skill
0  Implement user authentication  backend  spring boot
1    Optimize server performance  backend      asp.net
2     Manage database operations  backend       django
3  Implement user authentication  backend          api
4           Build a microservice  backend       kotlin
5    Optimize server performance  backend      laravel
6  Implement user authentication  backend  spring boot
7    Optimize server performance  backend            c
8    Optimize server performance  backend          C++
9    Optimize server performance  backend           go

In [8]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nUnique tasks:")
print(df["Task Description"].nunique())

print("\nUnique categories:")
print(df["Category"].nunique())

print("\nUnique skills:")
print(df["Skill"].nunique())

Rows: 20122
Columns: 3

Missing values:
Task Description    0
Category            0
Skill               0
dtype: int64

Duplicate rows:
19333

Unique tasks:
265

Unique categories:
13

Unique skills:
232

In [9]:
print("Categories:")
print(df["Category"].value_counts())

print("\nMost common skills:")
print(df["Skill"].value_counts().head(20))

Categories:
Category
backend                    2582
devops                     2582
testing                    2577
project management         2576
frontend                   1510
documentation              1505
deployment                 1505
database administration    1505
cloud                      1505
data science               1072
ui/ux design               1071
ai/ml                       127
database                      5
Name: count, dtype: int64

Most common skills:
Skill
aws             463
Python          453
azure           445
heroku          420
google cloud    404
SQL             361
kubernetes      317
node.js         314
firebase        307
docker          305
monitoring      280
JMeter          235
TensorFlow      231
Ansible         227
Adobe XD        226
UserTesting     224
Kubernetes      223
chai            220
Trello          220
Figma           220
Name: count, dtype: int64

In [10]:
df = df.dropna().copy()

df["Task Description"] = (
    df["Task Description"]
    .astype(str)
    .str.strip()
    .str.lower()
)

df["Category"] = (
    df["Category"]
    .astype(str)
    .str.strip()
    .str.lower()
)

df["Skill"] = (
    df["Skill"]
    .astype(str)
    .str.strip()
    .str.lower()
)

df = df.drop_duplicates()

print("Rows after cleaning:", len(df))

df.head()

Rows after cleaning: 782

                Task Description Category        Skill
0  implement user authentication  backend  spring boot
1    optimize server performance  backend      asp.net
2     manage database operations  backend       django
3  implement user authentication  backend          api
4           build a microservice  backend       kotlin

In [11]:
tasks = (
    df.groupby(
        ["Task Description", "Category"]
    )["Skill"]
    .apply(lambda x: sorted(set(x)))
    .reset_index()
)

tasks.columns = [
    "task_description",
    "category",
    "required_skills"
]

tasks["skill_count"] = (
    tasks["required_skills"].apply(len)
)

print("Unique tasks:", len(tasks))

tasks.head(10)

Unique tasks: 265

,task_description,category,required_skills,skill_count
0,add animations to improve ux,frontend,[gsap],1
1,allocate resources effectively,project management,[ms project],1
2,assign tasks to team members,project management,"[agile, collaboration tools, jira, kanban, mic...",8
3,automate ci/cd pipeline,devops,[jenkins],1
4,automate data augmentation for training images,ai/ml,[augmentor],1
5,automate deployment pipelines,devops,[ansible],1
6,automate deployment process,devops,"[ansible, bash, ci/cd, docker, git, jenkins, k...",10
7,automate deployment to heroku,cloud,[heroku],1
8,automate deployment using docker,deployment,[docker],1
9,automate infrastructure provisioning,devops,[terraform],1

In [12]:
PROJECT_TYPES = [
    "E-Commerce",
    "Social Media",
    "Healthcare",
    "Education",
    "Banking",
    "Food Delivery",
    "Project Management",
    "Booking System",
    "Inventory Management",
    "Portfolio Website"
]

In [ ]:
generated_rows = []

NUMBER_OF_PROJECTS = 500

for project_id in range(1, NUMBER_OF_PROJECTS + 1):

    project_type = random.choice(PROJECT_TYPES)

    team_size = random.randint(2, 8)

    number_of_tasks = random.randint(8, 20)

    selected_tasks = tasks.sample(
        n=min(number_of_tasks, len(tasks)),
        replace=False
    )

    previous_task = None

    for _, task in selected_tasks.iterrows():

        available_skills = task["required_skills"]

        number_of_skills = random.randint(
            1,
            min(4, len(available_skills))
        )

        selected_skills = random.sample(
            available_skills,
            number_of_skills
        )

        complexity = random.randint(1, 5)

        estimated_hours = random.randint(
            complexity * 2,
            complexity * 5
        )

        variation = random.randint(
            -2,
            complexity * 2
        )

        actual_hours = max(
            1,
            estimated_hours + variation
        )

        if complexity >= 4:
            priority = random.choice(
                ["high", "high", "medium"]
            )

        elif complexity == 3:
            priority = random.choice(
                ["medium", "high"]
            )

        else:
            priority = random.choice(
                ["low", "medium"]
            )

        deadline_days = random.randint(
            max(1, complexity),
            complexity * 3
        )

        dependency = (
            previous_task
            if random.random() < 0.35
            else None
        )

        delay_hours = max(
            0,
            actual_hours - estimated_hours
        )

        generated_rows.append({
            "project_id": project_id,
            "project_type": project_type,

            "task_description":
                task["task_description"],

            "category":
                task["category"],

            "required_skills": ",".join(selected_skills),
            "skill_count": len(selected_skills),

            "complexity":
                complexity,

            "priority":
                priority,

            "estimated_hours":
                estimated_hours,

            "actual_hours":
                actual_hours,

            "deadline_days":
                deadline_days,

            "team_size":
                team_size,

            "dependency":
                previous_task if dependency else "none",

            "delay_hours":
                delay_hours
        })

        previous_task = task["task_description"]

In [14]:
planify_df = pd.DataFrame(generated_rows)

print("Final dataset shape:", planify_df.shape)

planify_df.head(10)

Final dataset shape: (6862, 14)

,project_id,project_type,task_description,category,required_skills,skill_count,complexity,priority,estimated_hours,actual_hours,deadline_days,team_size,dependency,delay_hours
0,1,Social Media,manage cloud resources,cloud,azure,1,3,medium,9,10,8,2,none,1
1,1,Social Media,develop real-time video analytics for surveill...,ai/ml,yolov5,1,5,high,12,19,5,2,manage cloud resources,7
2,1,Social Media,design database schema,database administration,"cassandra,data,mongodb,mysql,oracle,postgresql...",10,2,low,5,7,6,2,develop real-time video analytics for surveill...,2
3,1,Social Media,build facial recognition model,ai/ml,dlib,1,5,high,23,24,14,2,design database schema,1
4,1,Social Media,automate infrastructure provisioning,devops,terraform,1,1,medium,3,4,2,2,build facial recognition model,1
5,1,Social Media,implement container orchestration,devops,kubernetes,1,3,high,7,6,3,2,none,0
6,1,Social Media,train text classification model,ai/ml,fasttext,1,3,medium,15,17,8,2,none,2
7,1,Social Media,conduct exploratory data analysis for ml project,ai/ml,pandas,1,1,medium,5,3,3,2,none,0
8,1,Social Media,migrate data to the cloud,database administration,"cassandra,data,mongodb,mysql,oracle,postgresql...",10,3,medium,15,16,3,2,none,1
9,1,Social Media,document code for open-source project,documentation,"api documentation,asciidoc,confluence,markdown...",8,3,medium,7,8,6,2,migrate data to the cloud,1

In [15]:
print("Rows:", len(planify_df))

print("\nMissing values:")
print(planify_df.isnull().sum())

print("\nCategories:")
print(planify_df["category"].value_counts())

print("\nPriorities:")
print(planify_df["priority"].value_counts())

print("\nComplexity:")
print(planify_df["complexity"].value_counts())

print("\nEstimated hours:")
print(planify_df["estimated_hours"].describe())

print("\nActual hours:")
print(planify_df["actual_hours"].describe())

Rows: 6862

Missing values:
project_id          0
project_type        0
task_description    0
category            0
required_skills     0
skill_count         0
complexity          0
priority            0
estimated_hours     0
actual_hours        0
deadline_days       0
team_size           0
dependency          0
delay_hours         0
dtype: int64

Categories:
category
ai/ml                      3221
backend                     494
devops                      455
testing                     406
frontend                    392
project management          375
deployment                  305
cloud                       288
documentation               283
database administration     267
database                    136
data science                135
ui/ux design                105
Name: count, dtype: int64

Priorities:
priority
medium    2967
high      2569
low       1326
Name: count, dtype: int64

Complexity:
complexity
3    1391
5    1390
4    1384
2    1358
1    1339
Name: count, dtype: int64

Estimated hours:
count    6862.000000
mean       10.632177
std         5.896271
min         2.000000
25%         5.000000
50%        10.000000
75%        15.000000
max        25.000000
Name: estimated_hours, dtype: float64

Actual hours:
count    6862.000000
mean       12.723696
std         7.635461
min         1.000000
25%         6.000000
50%        12.000000
75%        18.000000
max        35.000000
Name: actual_hours, dtype: float64

In [16]:
planify_df.sample(20)

,project_id,project_type,task_description,category,required_skills,skill_count,complexity,priority,estimated_hours,actual_hours,deadline_days,team_size,dependency,delay_hours
2120,158,Banking,build scalable microservices,backend,docker,1,4,medium,13,15,9,3,none,2
4555,337,Portfolio Website,train object detection model on custom dataset,ai/ml,faster r-cnn,1,1,low,5,4,2,6,none,0
2672,196,Inventory Management,build a time series forecasting model,ai/ml,prophet,1,5,high,18,24,8,6,develop fraud detection system,6
2042,153,Food Delivery,build a microservice,backend,"api,asp.net,c,c++,database,django,flask,go,jav...",18,3,high,6,12,5,6,build model for detecting diabetic retinopathy...,6
5083,376,Portfolio Website,develop personalized ad recommendation based o...,ai/ml,collaborative filtering,1,3,high,9,8,8,4,none,0
4248,315,Social Media,implement user authentication,backend,"api,asp.net,c,c++,database,django,flask,go,jav...",18,5,high,11,15,9,5,none,4
6792,496,Food Delivery,perform real-time anomaly detection on iot data,ai/ml,adtk,1,3,medium,7,10,4,8,conduct social network analysis,3
4480,332,Healthcare,build recommendation model with deep learning,ai/ml,deeprecsys,1,1,low,2,3,1,2,none,1
414,30,Banking,design a user-friendly interface,frontend,"angular,bootstrap,css,ember.js,foundation,html...",17,4,high,17,18,12,8,none,1
1768,131,Project Management,test frontend components,testing,jest,1,3,high,6,7,4,8,none,1
6374,466,Booking System,implement regression model for sales prediction,ai/ml,linear regression,1,4,high,15,23,6,6,none,8
3186,234,Social Media,develop recommendation system based on user ra...,ai/ml,als,1,5,medium,21,22,6,4,conduct ocr for scanned document processing,1
1295,95,E-Commerce,visualize data insights,data science,tableau,1,3,high,9,14,7,4,none,5
6071,446,Banking,deploy app on aws,cloud,"aws,azure,firebase,google cloud,heroku",5,3,medium,6,11,6,6,none,5
1835,136,Project Management,train model for text-to-image generation,ai/ml,dall-e,1,1,medium,3,4,2,2,none,1
4529,335,Booking System,automate infrastructure provisioning,devops,terraform,1,2,low,8,11,5,6,none,3
1345,99,Inventory Management,build a generative adversarial network (gan),ai/ml,tensorflow-gan,1,4,medium,14,19,11,4,none,5
1886,139,Project Management,manage infrastructure with terraform,devops,"ansible,bash,ci/cd,docker,git,jenkins,kubernet...",10,4,high,16,19,11,3,build predictive maintenance model for machinery,3
1102,80,Social Media,conduct user research,ui/ux design,usertesting,1,2,low,4,2,5,4,none,0
4987,369,Social Media,build speech-to-text model for voice commands,ai/ml,deepspeech,1,4,high,11,13,5,5,implement noise reduction in audio files,2